port 1194
proto tcp
dev tun

# Пути к файлам внутри будущей системы
ca /etc/openvpn/server/ca.crt
cert /etc/openvpn/server/vpn-server.crt
key /etc/openvpn/server/vpn-server.key
dh /etc/openvpn/server/dh.pem
tls-auth /etc/openvpn/server/ta.key 0

# Сетевые настройки (какую подсеть выдавать клиентам)
server 10.8.0.0 255.255.255.0

keepalive 10 120
persist-key
persist-tun
status openvpn-status.log
verb 3
